[project]
name = "paatashaala-data-loader-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "firebase-admin>=7.1.0",
    "openai>=1.107.2",
]
